### ISSUE TITLE
Mettre les TP au plus récent

### ISSUE THREAD

**Issue by Taliayaya** [BackToBasicsEpita/Programmation-Sup#19]
J'ai l'impression que les TP s'affichent un peu de façon random (ordre alphabétique) .
Est-ce voulu? J'ai le sentiment que les plus récents devraient s'afficher en premier

cf l'image
![image](https://github.com/BackToBasicsEpita/Programmation-Sup/assets/84530101/fa52765d-9c9e-4707-a092-f6ad2c007bfa)

**Comment by Gregoire-perso** [comment]
Ça a été fix entre temps
